import os

OBJECT_STORAGE_ENDPOINT = os.getenv("OBJECT_STORAGE_ENDPOINT")
OBJECT_STORAGE_ACCESS_KEY = os.getenv("OBJECT_STORAGE_ACCESS_KEY")
OBJECT_STORAGE_SECRET_KEY = os.getenv("OBJECT_STORAGE_SECRET_KEY")
DATASETS_BUCKET = os.getenv("DATASETS_BUCKET")
TRAINED_MODELS_BUCKET = os.getenv("TRAINED_MODELS_BUCKET")
